[supervisord]
nodaemon=true

[program:first-boot]
command=/usr/local/bin/first-boot.sh
autostart=true
startretries=3
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:emulator]
command=/usr/local/bin/emulator-runner.sh
autostart=true
startretries=3
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:ws-scrcpy]
directory=/opt/ws-scrcpy
command=npm start
autostart=false
startretries=0
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
