version: '3.8'
services:
  flutter:
    build:
      context: .
      dockerfile: docker/flutter/Dockerfile
    volumes:
      - .:/home/developer/app:cached
      - flutter_pub_cache:/home/developer/.pub-cache
      - gradle_cache:/home/developer/.gradle
      - android_sdk:/opt/android-sdk
    environment:
      - ANDROID_SDK_ROOT=/opt/android-sdk
      - CI=true
    networks:
      - android-net
    ports:
      - 8081:8081 # Flutter debug port (if using web or host-forwarding)
    tty: true
    stdin_open: true

  dockerify-android:
    container_name: dockerify-android
    image: shmayro/dockerify-android:latest
    build:
      context: ./docker/emulator
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - ./data:/data
      - ./extras:/extras
    environment:
      DNS: one.one.one.one
      # RAM_SIZE: 4096
      # Optional screen resolution in WIDTHxHEIGHT format
      #SCREEN_RESOLUTION: 720x720
      # Optional screen density (dpi)
      #SCREEN_DENSITY: 227
      ROOT_SETUP: 0 # set to 1 to enable rooting
      GAPPS_SETUP: 0 # set to 1 to install PICO GAPPS
    privileged: true
    devices:
      - /dev/kvm
    networks:
      - android-net

  scrcpy-web:
    container_name: scrcpy-web
    restart: unless-stopped
    image: shmayro/scrcpy-web:latest
    privileged: true
    ports:
      - 8000:8000
    depends_on:
      dockerify-android:
        condition: service_healthy
    command: >
      sh -c "
        adb connect dockerify-android:5555 &&
        npm start
      "
    networks:
      - android-net

volumes:
  flutter_pub_cache:
  gradle_cache:
  emulator_home:
  android_sdk:

networks:
  android-net:
    driver: bridge
