version: '3.8'

services:
  emulator:
    build:
      context: docker/emulator
      dockerfile: docker/emulator/Dockerfile.arm64
    privileged: true # required for nested virtualization in many setups
    volumes:
      - emulator_home:/home/android
      - android_sdk:/opt/android-sdk
    ports:
      - 5555:5555 # adb tcp
      - 5037:5037 # adb server
      - 5900:5900 # vnc
    networks:
      - android-net
    shm_size: '1gb'
    command: ["./start-emulator.arm64.sh"]